name: build

services:
  frontend:
    image: $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG_F
    build:
      context: ../app/frontend
    env_file: .env
    pull_policy: build
    ports:
      - "5173:5173"
  backend:
    image: $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG_B
    build:
      context: ../app/backend
    env_file: .env
    pull_policy: build
    ports:
      - "8800:8800"
