name: build

services:
  frontend:
    build:
      context: ../app/frontend
    image: $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG_F
    env_file: .env
    pull_policy: build
    ports:
      - "5173:5173"
    command: npm run preview --host 0.0.0.0
  backend:
    build:
      context: ../app/backend
    image: $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG_B
    env_file: .env
    pull_policy: build
    ports:
      - "8800:8800"
