name: Nightly

on:
  schedule:
  - cron: '0 8 * * *'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_FRONTEND: midterm/frontend
  ECR_REPOSITORY_BACKEND: midterm/backend

permissions:
  contents: read

jobs:
  verification:
    name: Verification through temp EC2
    runs-on: ubuntu-latest
    environment: Test-deployment
    steps:
    - name: Configure AWS CLI 2
      run: |
        cd ~/.aws
        echo "[default]\naws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}\naws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}\naws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" > credentials
        echo "[default]\nregion=${{ env.AWS_REGION }}\noutput=json" > config
        cat credentials
        cat config

    - name: Create temporary EC2
      run: |
        aws ec2 run-instances --image-id ami-04b4f1a9cf54c11d0 --count 1 --instance-type t2.micro --key-name MyKeyPair --security-group-ids sg-903004f8 --subnet-id subnet-6e7f829e

  ecr-deploy:
    name: Deploy to AWS ECR
    runs-on: ubuntu-latest
    if: ${{ jobs.verification.result == "success" }}
    environment: Test-deployment

    steps:
    - name: Checkout src
      uses: actions/checkout@v4
      with:
        repository: PaulMares/crud-react-node-mySQL-go
        path: ./app

    - name: Checkout infra
      uses: actions/checkout@v4
      with:
        path: ./infra

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG_F: ${{ github.sha }}
        IMAGE_TAG_B: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker compose -f ./infra/docker-compose.yml build
        docker images
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG_F
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG_B
