name: Nightly

on:
  schedule:
  - cron: '0 8 * * *'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

permissions:
  contents: read

jobs:
  verification:
    name: Verification through temp EC2
    runs-on: ubuntu-latest
    environment: Test-deployment
    steps:
    - name: Configure AWS CLI 2
      run: |
        cd ~/.aws
        echo "[default]\naws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}\naws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}\naws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" > credentials
        echo "[default]\nregion=${{ env.AWS_REGION }}\noutput=json" > config
        cat credentials
        cat config

    - name: Create temporary EC2
      run: |
        aws ec2 run-instances --image-id ami-04b4f1a9cf54c11d0 --count 1 --instance-type t2.micro --key-name MyKeyPair --security-group-ids sg-903004f8 --subnet-id subnet-6e7f829e
